#!/usr/bin/env bash
CONVERT=/usr/bin/ebook-convert
META=/usr/bin/ebook-meta
TITLE=${1?"missing book title!"}
EPUB=$(find $HOME/epub -regex ''.*/$TITLE.epub -print)
if [ ! -n "$EPUB" ]; then
exit 1
fi
echo $EPUB
if [ ! -d $TITLE ]; then
mkdir $TITLE
fi
cd $TITLE
AUTHOR=$($META $EPUB | grep Author | sed 's/^Author.*: \(.*\)/\1/')
echo $AUTHOR > author.txt
$CONVERT $EPUB  all.txt
opencc < all.txt > converted.txt
../d4_prepare_coverparameters ^第
../d4_mov_with
bash raylex.sh
BOOK=$(pwd | sed 's#.*/\([^/]*\)#\1#')
ZHTTS=/home/raylex/raylexlee.github.io/zhtts/text
if [[ -d $ZHTTS/$BOOK ]]; then :; else
  mkdir $ZHTTS/$BOOK
fi
for i in $(ls [0-9]*txt)
do
sed '/^\ *$/ d' < $i > $ZHTTS/$BOOK/$i
done
cp coverparameters.txt $ZHTTS/$BOOK/
