#!/usr/bin/env bash
BOOK=Emma
[ -d $BOOK ] || mkdir $BOOK
cd $BOOK
../getlinks.js 'https://en.wikisource.org/wiki/Emma_(Austen)' > temp.txt
vim temp.txt
cat temp.txt | sed -e 's/ /_/g' -e 's/_https:/ https:/' |  nl -n rz -w 3 -s " " > titlechapter.txt
cat titlechapter.txt | awk '{printf("../getwikisource_chapter %s '\''%s'\''\n",$1, $3)}' > raylex.sh
awk '{print $1,$2}' < titlechapter.txt > coverparameters.txt
sh raylex.sh
vim 001.txt
../create_entts_text

