#!/usr/bin/env bash
BOOK=${1?"missing book name..."}
LINK=${2?"missing link of book"}
[ -d $BOOK ] || mkdir $BOOK
cd $BOOK
../getlinks.js $LINK | ../decodeURI | grep '第[0-9][0-9]' > temp.txt
vim temp.txt
cat temp.txt | sed -e 's/ /_/g' -e 's/_https:/ https:/' |  nl -n rz -w 3 -s " " > titlechapter.txt
cat titlechapter.txt | awk '{printf("../gethantwikisource_chapter %s '\''%s'\''\n",$1, $3)}' > raylex.sh
awk '{print $1,$2}' < titlechapter.txt > coverparameters.txt
sh raylex.sh
#../create_entts_text
rm -rf 'C:\Users\rayle\AppData\Local\lighthouse'*
