#!/usr/bin/env bash
#../prepare_coverparameters ^第
../prepare_coverparameters △
#../prepare_coverparameters ^[^　]
../mov_with
bash raylex.sh
BOOK=$(pwd | sed 's#.*/\([^/]*\)#\1#')
ZHTTS=$HOME/Sites/zhtts/text
if [[ -d $ZHTTS/$BOOK ]]; then :; else
  mkdir $ZHTTS/$BOOK
fi
for i in $(ls [0-9]*txt)
do
sed '/^\ *$/ d' < $i > $ZHTTS/$BOOK/$i
done
sed 's/△//' < coverparameters.txt > $ZHTTS/$BOOK/coverparameters.txt
