#!/usr/bin/env zsh
AUTHOR=${1?'missing name of author or group...'}
BOOK=${2?'missing name of book...'}
FOLDER=${3-zhtts}
CHAPTER=${4-000}
start=$SECONDS
TEXTDIR=$HOME/Sites/$FOLDER/text/$BOOK
AUDIODIR=$HOME/Sites/$FOLDER/audio/$BOOK
#AUDIODIR=$HOME/audio/$BOOK
[ -d $AUDIODIR ] || mkdir $AUDIODIR
cd $AUDIODIR
LAST_CHAPTER=$(tail -1 $TEXTDIR/coverparameters.txt | sed 's#^\(...\).*#\1#')
while [ $CHAPTER -le $LAST_CHAPTER ]
do
VAR=$(grep ^$CHAPTER $TEXTDIR/coverparameters.txt)
if [ -n "$VAR" ]; then 
TITLE=$(echo $VAR | sed -e 's#\s#_#g' -e 's#^....\(.*\)#\1#' )
DATE=$(date +%F)
## for mac mini 2011
#say -r 30 -f $TEXTDIR/$CHAPTER.txt -o $CHAPTER.aiff
say -f $TEXTDIR/$CHAPTER.txt -o $CHAPTER.aiff
ffmpeg -hide_banner -i $CHAPTER.aiff -codec:a libmp3lame -qscale:a 9 -af "atempo=0.85" -metadata artist="$AUTHOR" -metadata title="$TITLE" -metadata album="【"$BOOK"】全本廣東話原文照讀" -metadata genre="101"  -metadata date=$DATE  -metadata track="$CHAPTER/$LAST_CHAPTER" $CHAPTER.mp3
rm $CHAPTER.aiff
ls -l
fi
CHAPTER=$(printf "%03d" `expr $CHAPTER + 1`)
done
final=$SECONDS
echo Time elapsed : $((final - start)) seconds
