#!/usr/bin/env bash
BOOK=${1?"missing book name"}
if [[ -d $BOOK ]]; then
cd $BOOK
else
echo the folder $BOOK does not exist!
exit 1
fi
if [[ -d text ]]; then :; else  
  mkdir text
fi  
for i in $(ls [0-9]*txt)
do
sed -e '/^\ *$/ d' -e 's/什./甚麼/g' < $i > text/$i
done
cp coverparameters.txt text/

