scp -P 53178 -r public/text/孤獨的進化者 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/中國2185 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/魔鬼積木 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/蟲子的世界 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/2.5次世界大戰 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/科幻之書4·詩云 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/三體Ⅲ·死神永生 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/三體Ⅱ·黑暗森林 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/三體 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/劉慈欣科幻作品集 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/鏡子 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/超新星紀元 www.tingshucantonese.net:html/yodu/text/
scp -P 53178 -r public/text/球狀閃電 www.tingshucantonese.net:html/yodu/text/
