#!/usr/bin/env bash
#REGEX=${1-^　　第.[一二三四五六七八九十卷]}
#REGEX=${1-^　　[（第][0-9四][0-9十][章）]}
#REGEX=${1-^　　第.[一二三四五六七八九十章]}
#REGEX=${1-^[東這終後最作鞠雙忍序番第解關導推１２３４５６７８９０]}
#REGEX=${1-^[１２３４５６７８９０]}
#REGEX=${1-^　　[一二三四五六七八九十]*$}
#REGEX=${1-^[^　]}
REGEX=${1-^[第附後]}
#REGEX=${1-^[^　一二三四五六七八十][^、]}
grep $REGEX converted.txt | nl -n rz -w 3 -s " " > coverparameters.txt 
node ../getlast_chapter.js > last_chapter.txt
csplit -k -n 3 converted.txt "/$REGEX/" '{9999}'
rm xx000
