#!/usr/bin/env bash
CONVERT=/usr/bin/ebook-convert
META=/usr/bin/ebook-meta
#CONVERT=/Applications/calibre.app/Contents/MacOS/ebook-convert
#META=/Applications/calibre.app/Contents/MacOS/ebook-meta
TITLE=${1?"missing book title!"}
#EPUB=$(find $HOME/epub -regex ''.*/$TITLE.epub -print)
EPUB=$(find /mnt/c/Users/rayle/Downloads/ -regex ''.*/$TITLE.epub -print)
if [ ! -n "$EPUB" ]; then
exit 1
fi
echo $EPUB
if [ ! -d $TITLE ]; then
mkdir $TITLE
fi
cd $TITLE
AUTHOR=$($META $EPUB | grep Author | sed 's/^Author.*: \(.*\)/\1/')
echo $AUTHOR > author.txt
$CONVERT $EPUB  all.txt
opencc < all.txt > converted.txt
#../prepare_coverparameters ^第
../prepare_coverparameters ^△
#../prepare_coverparameters ^〈
../mov_with
bash raylex.sh
BOOK=$(pwd | sed 's#.*/\([^/]*\)#\1#')
ZHTTS=$HOME/raylexlee.github.io/zhtts/text
if [[ -d $ZHTTS/$BOOK ]]; then :; else
  mkdir $ZHTTS/$BOOK
fi
for i in $(ls [0-9]*txt)
do
sed '/^\ *$/ d' < $i > $ZHTTS/$BOOK/$i
done
#cp coverparameters.txt $ZHTTS/$BOOK/
sed 's/△//' < coverparameters.txt > $ZHTTS/$BOOK/coverparameters.txt
#sed 's/[〈〉〔〕]//g' < coverparameters.txt > $ZHTTS/$BOOK/coverparameters.txt
