#!/usr/bin/env bash
CONVERT=/usr/bin/ebook-convert
META=/usr/bin/ebook-meta
#CONVERT=/Applications/calibre.app/Contents/MacOS/ebook-convert
#META=/Applications/calibre.app/Contents/MacOS/ebook-meta
TITLE=${1?"missing book title!"}
EPUB=$(find $HOME/epub -regex ''.*/$TITLE.epub -print)
#EPUB=$(find /mnt/c/Users/rayle/Downloads/ -regex ''.*/$TITLE.epub -print)
if [ ! -n "$EPUB" ]; then
exit 1
fi
echo $EPUB
if [ ! -d $TITLE ]; then
mkdir $TITLE
fi
cd $TITLE
AUTHOR=$($META $EPUB | grep Author | sed 's/^Author.*: \(.*\)/\1/')
echo $AUTHOR > author.txt
$CONVERT $EPUB  all.txt
opencc < all.txt > converted.txt
vim converted.txt
